/**
 * DỮ LIỆU ĐẦY ĐỦ VỀ 16 QUỐC GIA & BINH CHỦNG TỪNG ĐỜI (ĐỜI 1 - ĐỜI 4) TRONG AOE 1
 */

// 1. DỮ LIỆU 16 QUỐC GIA CHI TIẾT KÈM HÌNH ẢNH MINH HỌA
const AOE_CIVILIZATIONS = [
  {
    id: "shang",
    name: "Shang",
    nameVi: "Thương",
    nameCn: "商",
    icon: "🏹",
    image: "images/civs/shang.svg",
    bannerColor: "#881337",
    architecture: "Đông Á (East Asian)",
    specialBonus: [
      "Nông dân rẻ nhất game: 35 thực (so với 50 thực chuẩn)",
      "Tường thành (Wall) gấp đôi lượng máu (x2 HP)",
      "Tốc độ ép đời chuẩn, ít khi bị đứt dân do thiếu thực"
    ],
    weakness: "Chỉ số quân đội không có điểm cộng công/tốc độ; đời 4 thiếu Voi, Cẩu đá to, Ngựa đạp đôi và Ngựa chém thần.",
    unitsByAge: {
      age1: ["Nông dân 35 thực", "Lính chùy"],
      age2: ["Ngựa dò", "Lính rìu", "Cung trần"],
      age3: ["Cung R (BA chuẩn mực)", "Ngựa chém (BL)", "Sọc đơn", "Phù thủy"],
      age4: ["Lính BB chém (Legion)", "Bắn đá nhỏ (Onager)", "Ngựa chém giáp 4"]
    },
    tierSolo: "S+",
    tierTeam: "A",
    playStyle: "Đỉnh cao của ép đời và đánh Cung R chuẩn mực; thao tác vi mô kiểm soát thế trận hàng đầu.",
    techTree: {
      wheel: true,
      chariotArcher: true,
      nobility: true,
      cavalry: true,
      scytheChariot: false,
      cataphract: false,
      compositeBowman: true,
      horseArcher: true,
      elephant: false,
      heavyCatapult: false,
      helepolis: false,
      centurion: false,
      priest: true,
      ballistaTower: false
    }
  },
  {
    id: "assyrian",
    name: "Assyrian",
    nameVi: "Áp-si / A-si",
    nameCn: "亚述",
    icon: "⚡",
    image: "images/civs/assyrian.svg",
    bannerColor: "#0284c7",
    architecture: "Babylon / Lưỡng Hà",
    specialBonus: [
      "Nông dân di chuyển nhanh hơn +30% (tương đương tốc độ ngựa dò)",
      "Cung R bắn nhanh hơn +33% (tần suất ra tên dày đặc nhất game)",
      "Dân chạy nhanh giúp câu voi, lùa hươu và trốn thú dữ an toàn tuyệt đối"
    ],
    weakness: "Không có nâng cấp Đầu Máu (Nobility) ở BM -> Cung R chỉ có 75 máu. Đời 4 yếu nhất game, thiếu hầu hết công nghệ hủy diệt.",
    unitsByAge: {
      age1: ["Nông dân chạy nhanh +30%", "Lính chùy"],
      age2: ["Ngựa dò", "Lính rìu", "Cung trần"],
      age3: ["Cung R (bắn nhanh +33%)", "Phù thủy", "Sọc đơn"],
      age4: ["Lính BB kiếm", "Cẩu đá nhỏ (rất yếu ở Đời 4)"]
    },
    tierSolo: "S+",
    tierTeam: "S",
    playStyle: "Bá vương Cung R đời 3; ép đời thần tốc và quản lý bản đồ siêu rộng; xả tên dày đặc ép nghẹt thở.",
    techTree: {
      wheel: true,
      chariotArcher: true,
      nobility: false,
      cavalry: false,
      scytheChariot: false,
      cataphract: false,
      compositeBowman: true,
      horseArcher: false,
      elephant: false,
      heavyCatapult: false,
      helepolis: false,
      centurion: false,
      priest: true,
      ballistaTower: false
    }
  },
  {
    id: "egyptian",
    name: "Egyptian",
    nameVi: "Ai Cập",
    nameCn: "埃及",
    icon: "🛡️",
    image: "images/civs/egyptian.svg",
    bannerColor: "#eab308",
    architecture: "Ai Cập (Egyptian)",
    specialBonus: [
      "Cung R được +33% HP (93 máu trâu nhất game)",
      "Dân đào vàng mang về 13 vàng/chuyến (+20% tốc độ khai thác)",
      "Phù thủy tầm xa +3 (12 ở đời 3, 15-16 ở đời 4)"
    ],
    weakness: "Không có Ngựa chém BL, không có Voi, không có Lính Xiên; đầu đời 3 dễ thiếu gỗ nếu ép nhiều nhà BA.",
    unitsByAge: {
      age1: ["Nông dân đào vàng nhanh", "Lính chùy"],
      age2: ["Ngựa dò", "Lính rìu", "Cung trần"],
      age3: ["Cung R (93 máu trâu bò)", "Phù thủy tầm xa 12", "Sọc đơn"],
      age4: ["Ngựa đạp đôi max công nghệ", "Phù thủy sấm sét", "Cẩu đá to (Heavy Catapult)"]
    },
    tierSolo: "S",
    tierTeam: "S",
    playStyle: "Cung R 93 máu đổi mạng cực hời ở đời 3; Đời 4 là thế lực toàn diện với Đạp đôi kẹp Cẩu đá to và Phù thủy sét.",
    techTree: {
      wheel: true,
      chariotArcher: true,
      nobility: true,
      cavalry: false,
      scytheChariot: true,
      cataphract: false,
      compositeBowman: true,
      horseArcher: false,
      elephant: false,
      heavyCatapult: true,
      helepolis: true,
      centurion: false,
      priest: true,
      ballistaTower: true
    }
  },
  {
    id: "babylonian",
    name: "Babylonian",
    nameVi: "Ba-bi-lon",
    nameCn: "巴比伦",
    icon: "🏰",
    image: "images/civs/babylonian.svg",
    bannerColor: "#6366f1",
    architecture: "Babylon / Lưỡng Hà",
    specialBonus: [
      "Tường thành và Tháp canh (Chòi) gấp đôi máu (x2 HP)",
      "Phù thủy hồi phục năng lượng (mana) nhanh hơn +30%",
      "Dân đào đá mang về 13 đá/chuyến (+3 đá)"
    ],
    weakness: "Không có bonus di chuyển nhanh hay cộng sát thương trực tiếp cho quân đội ở đầu trận.",
    unitsByAge: {
      age1: ["Nông dân đào đá nhanh", "Lính chùy"],
      age2: ["Ngựa dò", "Tháp canh x2 máu", "Cung trần"],
      age3: ["Cung R", "Ngựa chém BL", "Sọc đơn", "Phù thủy hồi mana nhanh"],
      age4: ["Đạp đôi", "Cung A 3 áo", "Cẩu đá to", "Chòi thần 1000 HP"]
    },
    tierSolo: "A",
    tierTeam: "A",
    playStyle: "Thủ nhà dẻo dai, bền bỉ; Đời 4 công thủ toàn diện với Chòi thần 1000 HP và Cẩu đá to.",
    techTree: {
      wheel: true,
      chariotArcher: true,
      nobility: true,
      cavalry: true,
      scytheChariot: true,
      cataphract: false,
      compositeBowman: true,
      horseArcher: true,
      elephant: false,
      heavyCatapult: true,
      helepolis: true,
      centurion: false,
      priest: true,
      ballistaTower: true
    }
  },
  {
    id: "hittite",
    name: "Hittite",
    nameVi: "Hít-ti",
    nameCn: "西台 / 赫梯",
    icon: "☄️",
    image: "images/civs/hittite.svg",
    bannerColor: "#d97706",
    architecture: "Babylon / Lưỡng Hà",
    specialBonus: [
      "Tất cả cung nhà BA mặc định +1 công (Cung T công 4, Cung R công 5, Cung A công 6, Cung C công 9)",
      "Cẩu đá (Stone Thrower, Catapult) x2 lượng máu (300 HP đời 3, 350 HP đời 4)",
      "Tàu chiến tầm xa +4"
    ],
    weakness: "Không có Cẩu đá to nhất (Heavy Catapult), không thể xây Đền thờ / Phù thủy (BP).",
    unitsByAge: {
      age1: ["Nông dân", "Lính chùy"],
      age2: ["Ngựa dò", "Lính rìu", "Cung trần (+1 công)"],
      age3: ["Cung R (+1 công cực rát)", "Cẩu đá 300 HP trâu bò", "Ngựa chém BL"],
      age4: ["Cung R lửa", "Đạp đôi", "Cẩu đá 350 HP kẹp Cung", "Ngựa chém giáp 4"]
    },
    tierSolo: "S",
    tierTeam: "S+",
    playStyle: "Chủ lực hoàn hảo nhất bản đồ Random; Cung R bắn đau cắn dân siêu nhanh, Cẩu đá x2 máu dẹp tan dàn cung địch.",
    techTree: {
      wheel: true,
      chariotArcher: true,
      nobility: true,
      cavalry: true,
      scytheChariot: true,
      cataphract: false,
      compositeBowman: true,
      horseArcher: true,
      elephant: false,
      heavyCatapult: false,
      helepolis: true,
      centurion: false,
      priest: false,
      ballistaTower: true
    }
  },
  {
    id: "phoenician",
    name: "Phoenician",
    nameVi: "Phê-nê",
    nameCn: "腓尼基",
    icon: "🌲",
    image: "images/civs/phoenician.svg",
    bannerColor: "#059669",
    architecture: "Babylon / Lưỡng Hà",
    specialBonus: [
      "Dân chặt gỗ mang về 13 gỗ (+3 gỗ/chuyến, tích lũy gỗ siêu nhanh)",
      "Voi húc và Voi tên giảm 25% giá thực (Voi húc 127.5 thực, Voi tên 135 thực)",
      "Tàu chiến bắn nhanh hơn +65%"
    ],
    weakness: "Giáp lính bình thường, không có Đạp đôi, không có Cẩu đá to đời 4.",
    unitsByAge: {
      age1: ["Nông dân làm gỗ siêu nhanh", "Lính chùy"],
      age2: ["Ngựa dò", "Lính rìu", "Cung trần"],
      age3: ["Cung R (ra quân ồ ạt nhờ dồi dào gỗ)", "Ngựa chém BL", "Sọc đơn"],
      age4: ["Voi húc (127.5F) & Voi tên (135F) giá rẻ siêu đông", "Cung R lửa", "Cẩu đá nhỏ"]
    },
    tierSolo: "A",
    tierTeam: "S",
    playStyle: "Tốc độ tích lũy gỗ và cơ cấu ruộng thần tốc; đời 4 đàn Voi giá rẻ đè bẹp đối thủ.",
    techTree: {
      wheel: true,
      chariotArcher: true,
      nobility: true,
      cavalry: true,
      scytheChariot: false,
      cataphract: false,
      compositeBowman: true,
      horseArcher: true,
      elephant: true,
      heavyCatapult: false,
      helepolis: true,
      centurion: true,
      priest: true,
      ballistaTower: false
    }
  },
  {
    id: "sumerian",
    name: "Sumerian",
    nameVi: "Su-me / Xume",
    nameCn: "苏美尔",
    icon: "🌾",
    image: "images/civs/sumerian.svg",
    bannerColor: "#ca8a04",
    architecture: "Babylon / Lưỡng Hà",
    specialBonus: [
      "Dân có 40 HP (trâu hơn 60% dân thường, chống sư tử/ngựa dò chém dân cực tốt)",
      "Ruộng có gấp đôi sản lượng (500 thực thay vì 250 thực)",
      "Cẩu đá (Catapult) bắn nhanh gấp đôi (x2 attack speed)"
    ],
    weakness: "Không có Voi, không có Ngựa đôi, không có Cung lửa đời 4.",
    unitsByAge: {
      age1: ["Nông dân 40 máu trâu bò", "Lính chùy"],
      age2: ["Ngựa dò", "Lính rìu", "Cung trần"],
      age3: ["Cung R (tiết kiệm gỗ vẽ ruộng)", "Ngựa chém BL", "Cẩu đá bắn nhanh x2"],
      age4: ["Cẩu đá to bắn liên thanh", "Đạp đôi", "Ngựa chém giáp 4"]
    },
    tierSolo: "A+",
    tierTeam: "S",
    playStyle: "Dân 40 máu khó bị bắt lẻ; khả năng hồi phục kinh tế bền bỉ; Cẩu đá bắn liên thanh giải tán đám đông trong nháy mắt.",
    techTree: {
      wheel: true,
      chariotArcher: true,
      nobility: true,
      cavalry: true,
      scytheChariot: true,
      cataphract: false,
      compositeBowman: true,
      horseArcher: true,
      elephant: false,
      heavyCatapult: true,
      helepolis: true,
      centurion: true,
      priest: true,
      ballistaTower: false
    }
  },
  {
    id: "persian",
    name: "Persian",
    nameVi: "Ba Tư",
    nameCn: "波斯",
    icon: "🐘",
    image: "images/civs/persian.svg",
    bannerColor: "#854d0e",
    architecture: "Babylon / Lưỡng Hà",
    specialBonus: [
      "Dân ăn hươu và voi nhanh hơn +30%",
      "Voi di chuyển nhanh hơn +50% (chạy thần tốc như ngựa)",
      "Bị trừ 50 thực lúc bắt đầu trận (chỉ có 150 thực khởi điểm)"
    ],
    weakness: "Không có Bánh xe (không có Cung R, không có Đạp đôi); khởi đầu bị trừ 50 thực cần dò quả sớm.",
    unitsByAge: {
      age1: ["Nông dân ăn thịt nhanh", "Lính chùy"],
      age2: ["Ngựa dò", "Lính rìu", "Cung trần"],
      age3: ["Ngựa chém BL kích sớm", "Lạc đà (khắc chém)", "Cung A 2 áo"],
      age4: ["Voi điên (Voi húc chạy như bay)", "Cung A 3 áo", "Cẩu đá to"]
    },
    tierSolo: "B+",
    tierTeam: "A+",
    playStyle: "Đầu đời 3 chém cực rát nếu ép đời chuẩn; Đời 4 Voi điên chạy nhanh là ác mộng của mọi đối thủ.",
    techTree: {
      wheel: false,
      chariotArcher: false,
      nobility: true,
      cavalry: true,
      scytheChariot: false,
      cataphract: false,
      compositeBowman: true,
      horseArcher: false,
      elephant: true,
      heavyCatapult: true,
      helepolis: true,
      centurion: true,
      priest: true,
      ballistaTower: false
    }
  },
  {
    id: "yamato",
    name: "Yamato",
    nameVi: "Nhật Bản",
    nameCn: "大和",
    icon: "⚔️",
    image: "images/civs/yamato.svg",
    bannerColor: "#dc2626",
    architecture: "Đông Á (East Asian)",
    specialBonus: [
      "Tất cả kỵ binh (Ngựa dò, Ngựa chém, Chém thần, Cung C) giảm 25% chi phí (cả thực và vàng)",
      "Tàu chiến tăng +30% lượng máu (HP)"
    ],
    weakness: "Không có Cẩu đá nhà BK; Đời 4 không có Đạp đôi, không có Voi, Cung R yếu (không giáp tên).",
    unitsByAge: {
      age1: ["Nông dân chuẩn 50 thực", "Lính chùy"],
      age2: ["Ngựa dò giá rẻ 75 thực", "Lính rìu", "Cung trần"],
      age3: ["Ngựa chém BL (52.5 thực, 60 vàng - Vua ép chém)", "Cung A", "Phù thủy"],
      age4: ["Ngựa chém thần (Cataphract 52.5 thực, 60 vàng)", "Cung C thần rẻ", "Xiên thần"]
    },
    tierSolo: "S",
    tierTeam: "S",
    playStyle: "Vua của chiến thuật đánh Chém đời 3; giảm 25% chi phí giúp đẻ chém liên tục không ngắt nhịp; solo Yamato đỉnh cao.",
    techTree: {
      wheel: true,
      chariotArcher: true,
      nobility: true,
      cavalry: true,
      scytheChariot: false,
      cataphract: true,
      compositeBowman: true,
      horseArcher: true,
      elephant: false,
      heavyCatapult: false,
      helepolis: true,
      centurion: true,
      priest: true,
      ballistaTower: false
    }
  },
  {
    id: "minoan",
    name: "Minoan",
    nameVi: "Mi-nô-an",
    nameCn: "米诺斯",
    icon: "🎯",
    image: "images/civs/minoan.svg",
    bannerColor: "#0284c7",
    architecture: "Hy Lạp (Greek)",
    specialBonus: [
      "Cung A (Composite Bowman) tầm xa +2 (khởi điểm 9 ô ở đời 3, tối đa 11 ô ở đời 4)",
      "Ruộng rẻ hơn 33% (chỉ tốn 50 gỗ thay vì 75 gỗ)",
      "Tàu chiến rẻ hơn 33%"
    ],
    weakness: "Không có Cung R, không có Ngựa chém BL, không có Lạc đà; phụ thuộc vào việc giữ được dàn Cung A không bị áp sát.",
    unitsByAge: {
      age1: ["Nông dân", "Lính chùy"],
      age2: ["Ngựa dò", "Lính rìu", "Cung trần"],
      age3: ["Cung A (tầm xa 9 bắn siêu xa)", "Cẩu đá", "Sọc đơn"],
      age4: ["Cung A lửa tầm xa 11", "Cẩu đá to", "Pháo tép Helepolis", "Đạp đôi"]
    },
    tierSolo: "A",
    tierTeam: "S",
    playStyle: "Vua Cung A; dàn Cung A Minoan đứng tụ sau lưng tạo bức tường tên bất khả xâm phạm, bắn gục quân địch từ khoảng cách cực xa.",
    techTree: {
      wheel: true,
      chariotArcher: false,
      nobility: true,
      cavalry: false,
      scytheChariot: true,
      cataphract: false,
      compositeBowman: true,
      horseArcher: false,
      elephant: false,
      heavyCatapult: true,
      helepolis: true,
      centurion: true,
      priest: true,
      ballistaTower: false
    }
  },
  {
    id: "choson",
    name: "Choson",
    nameVi: "Triều Tiên",
    nameCn: "朝鲜",
    icon: "🛡️",
    image: "images/civs/choson.svg",
    bannerColor: "#475569",
    architecture: "Đông Á (East Asian)",
    specialBonus: [
      "Lính BB kiếm (Swordsman / Legion) được +80 HP (tối đa 240 HP)",
      "Phù thủy giảm 30% giá vàng (chỉ 85 vàng thay vì 125 vàng)",
      "Tháp canh (Chòi) tầm xa +2"
    ],
    weakness: "Không có Bánh xe (không Cung R, không Đạp đôi); Ngựa chém không có Đầu máu; đời 3 đánh rất khó khăn.",
    unitsByAge: {
      age1: ["Nông dân", "Lính chùy"],
      age2: ["Ngựa dò", "Lính rìu", "Cung trần", "Chòi +2 tầm xa"],
      age3: ["Ngựa chém cơ bản", "Phù thủy rẻ", "Cung A", "BB kẹp Phù thủy"],
      age4: ["BB chém thần 240 HP (Legion siêu trâu)", "Phù thủy siêu rẻ", "Chòi thần xa"]
    },
    tierSolo: "C",
    tierTeam: "B+",
    playStyle: "Đời 3 khó xoay xở; nhưng Đời 4 lính BB 240 máu cùng dàn Phù thủy giá rẻ là lực lượng càn quét cực kỳ khủng khiếp.",
    techTree: {
      wheel: false,
      chariotArcher: false,
      nobility: false,
      cavalry: true,
      scytheChariot: false,
      cataphract: false,
      compositeBowman: true,
      horseArcher: false,
      elephant: false,
      heavyCatapult: true,
      helepolis: true,
      centurion: true,
      priest: true,
      ballistaTower: true
    }
  },
  {
    id: "roman",
    name: "Roman",
    nameVi: "La Mã",
    nameCn: "罗马",
    icon: "🔨",
    image: "images/civs/roman.svg",
    bannerColor: "#b91c1c",
    architecture: "La Mã (Roman)",
    specialBonus: [
      "Công trình rẻ hơn 15% gỗ (trừ tường và tháp canh)",
      "Tháp canh (Chòi) giảm 50% đá (chỉ tốn 75 đá)",
      "Lính BB kiếm chém nhanh hơn +33%"
    ],
    weakness: "Không có Bánh xe (không Cung R, không Đạp đôi); không có Cẩu đá to đời 4.",
    unitsByAge: {
      age1: ["Nông dân đóng nhà rẻ gỗ", "Lính chùy"],
      age2: ["Ngựa dò", "Chòi giảm 50% đá", "Lính rìu"],
      age3: ["Ngựa chém BL", "BB kiếm chém nhanh", "Dâng chòi (Tower Rush)", "Cung A"],
      age4: ["BB chém thần (Legion máy khâu)", "Ngựa chém thần (Cataphract)", "Pháo tép Helepolis"]
    },
    tierSolo: "B",
    tierTeam: "A",
    playStyle: "Tiết kiệm lượng gỗ khổng lồ; dâng chòi và đánh BB kiếm quấy rối rất khó chịu; lính kiếm chém nhanh như máy khâu.",
    techTree: {
      wheel: false,
      chariotArcher: false,
      nobility: true,
      cavalry: true,
      scytheChariot: false,
      cataphract: true,
      compositeBowman: true,
      horseArcher: false,
      elephant: false,
      heavyCatapult: false,
      helepolis: true,
      centurion: true,
      priest: true,
      ballistaTower: true
    }
  },
  {
    id: "carthaginian",
    name: "Carthaginian",
    nameVi: "Cát-ta / Cạc-ta",
    nameCn: "迦太基",
    icon: "🐘",
    image: "images/civs/carthaginian.svg",
    bannerColor: "#7c2d12",
    architecture: "La Mã (Roman)",
    specialBonus: [
      "Voi (húc & tên) và Lính Xiên (Hoplite) +25% HP (Voi 750 HP, Xiên 150-200 HP)",
      "Tháp canh lửa +50% sát thương",
      "Tàu chiến di chuyển nhanh hơn +30%"
    ],
    weakness: "Không có Bánh xe (không Cung R, không Đạp đôi); không có Ngựa chém BL.",
    unitsByAge: {
      age1: ["Nông dân", "Lính chùy"],
      age2: ["Ngựa dò", "Lính rìu", "Cung trần"],
      age3: ["Lạc đà (chống chém)", "Lính Xiên 150 HP", "Cung A"],
      age4: ["Voi húc 750 HP (máu dày nhất game)", "Xiên thần 200 HP", "Pháo lùn"]
    },
    tierSolo: "B",
    tierTeam: "A",
    playStyle: "Bậc thầy cận chiến hạng nặng; Voi 750 máu và Xiên thần 200 máu có thể ủi nát bất kỳ hàng phòng ngự kiên cố nào.",
    techTree: {
      wheel: false,
      chariotArcher: false,
      nobility: true,
      cavalry: false,
      scytheChariot: false,
      cataphract: false,
      compositeBowman: true,
      horseArcher: false,
      elephant: true,
      heavyCatapult: true,
      helepolis: true,
      centurion: true,
      priest: true,
      ballistaTower: true
    }
  },
  {
    id: "palmyran",
    name: "Palmyran",
    nameVi: "Pan-mi-ra",
    nameCn: "帕尔米拉",
    icon: "🐪",
    image: "images/civs/palmyran.svg",
    bannerColor: "#0d9488",
    architecture: "La Mã (Roman)",
    specialBonus: [
      "Dân làm việc nhanh hơn +20% trên mọi loại tài nguyên",
      "Dân có sẵn 1 giáp (chống chém và thú dữ tốt)",
      "Bơm tài nguyên cho đồng minh thuế 0% (free tax)",
      "Lạc đà di chuyển nhanh nhất game"
    ],
    weakness: "Dân đắt 75 thực/con (gấp rưỡi bình thường); mất dân đầu game là thảm họa khó gượng lại.",
    unitsByAge: {
      age1: ["Nông dân làm việc +20%, có 1 giáp (75 thực)", "Lính chùy"],
      age2: ["Ngựa dò", "Lính rìu", "Cung trần"],
      age3: ["Lạc đà siêu tốc (khắc tinh chém)", "Cung R", "Ngựa chém BL"],
      age4: ["Đạp đôi", "Cung R lửa", "Bắn đá to"]
    },
    tierSolo: "A+",
    tierTeam: "A+",
    playStyle: "Phát triển kinh tế siêu tốc nếu giữ dân tốt; Lạc đà Palmyra chạy lướt gió bắt gọn mọi loại ngựa chém.",
    techTree: {
      wheel: true,
      chariotArcher: true,
      nobility: true,
      cavalry: true,
      scytheChariot: true,
      cataphract: false,
      compositeBowman: true,
      horseArcher: false,
      elephant: false,
      heavyCatapult: true,
      helepolis: true,
      centurion: true,
      priest: true,
      ballistaTower: false
    }
  },
  {
    id: "macedonian",
    name: "Macedonian",
    nameVi: "Ma-xê-đô-ni-a",
    nameCn: "马其顿",
    icon: "🧙‍♂️",
    image: "images/civs/macedonian.svg",
    bannerColor: "#4f46e5",
    architecture: "La Mã (Roman)",
    specialBonus: [
      "Toàn bộ quân đội kháng Phù thủy gấp 4 lần",
      "Lính bộ binh và Bắn đá có tầm nhìn +2 LOS",
      "Pháo cẩu và Pháo lùn giảm 50% chi phí sản xuất"
    ],
    weakness: "KHÔNG CÓ NHÀ CHỢ (BM) -> Không thể nâng cấp Bánh xe, không nâng cấp Chặt gỗ, không bơm tài nguyên, không đào vàng/đá nhanh.",
    unitsByAge: {
      age1: ["Nông dân", "Lính chùy"],
      age2: ["Ngựa dò", "Lính rìu"],
      age3: ["Ngựa chém BL (trâu kháng hú)", "Lính Xiên", "Bắn đá rẻ 50%"],
      age4: ["Xiên thần", "Pháo lùn Helepolis siêu rẻ", "Bắn đá kẹp Xiên"]
    },
    tierSolo: "B+",
    tierTeam: "A",
    playStyle: "Khắc tinh tuyệt đối của các bài Phù thủy; Pháo rẻ như cho giúp dựng bức tường hỏa lực tầm xa áp đảo.",
    techTree: {
      wheel: false,
      chariotArcher: false,
      nobility: false,
      cavalry: true,
      scytheChariot: false,
      cataphract: false,
      compositeBowman: false,
      horseArcher: false,
      elephant: false,
      heavyCatapult: true,
      helepolis: true,
      centurion: true,
      priest: false,
      ballistaTower: false
    }
  },
  {
    id: "greek",
    name: "Greek",
    nameVi: "Hy Lạp",
    nameCn: "希腊",
    icon: "🔱",
    image: "images/civs/greek.svg",
    bannerColor: "#2563eb",
    architecture: "Hy Lạp (Greek)",
    specialBonus: [
      "Lính Xiên (Hoplite, Phalanx, Centurion) chạy nhanh hơn +30%",
      "Tàu chiến di chuyển nhanh hơn +30%"
    ],
    weakness: "Không có Bánh xe, không có Ngựa chém BL, không có Lạc đà, không có Voi; duy trì quân cực kỳ tốn vàng.",
    unitsByAge: {
      age1: ["Nông dân", "Lính chùy"],
      age2: ["Ngựa dò", "Lính rìu", "Cung trần"],
      age3: ["Lính Xiên chạy nhanh", "Cung A", "Phù thủy", "Sọc đơn"],
      age4: ["Xiên thần (Centurion) lướt gió", "Cẩu đá to", "Pháo lùn Helepolis"]
    },
    tierSolo: "C+",
    tierTeam: "B+",
    playStyle: "Vua lính Xiên; Xiên Greek đời 4 chạy nhanh như lướt gió áp sát tiêu diệt nhanh cả cung thủ lẫn pháo đối phương.",
    techTree: {
      wheel: false,
      chariotArcher: false,
      nobility: false,
      cavalry: false,
      scytheChariot: false,
      cataphract: false,
      compositeBowman: true,
      horseArcher: false,
      elephant: false,
      heavyCatapult: true,
      helepolis: true,
      centurion: true,
      priest: true,
      ballistaTower: true
    }
  }
];

// 2. DỮ LIỆU BINH CHỦNG TỪNG ĐỜI (ĐỜI 1 -> ĐỜI 4) KÈM CHI PHÍ & CHỈ SỐ TOÀN DIỆN
const AOE_UNITS_BY_AGE = [
  // ==================== ĐỜI 1: STONE AGE ====================
  {
    id: "villager",
    name: "Nông Dân (Dân)",
    nameEn: "Villager",
    age: 1,
    ageName: "Đời 1 (Stone Age)",
    building: "Nhà Chính (TC)",
    icon: "👨‍🌾",
    image: "images/units/villager.png",
    category: "kinh-te",
    cost: { food: 50, wood: 0, gold: 0, stone: 0 },
    costText: "50 Thực (Shang 35, Pal 75)",
    hp: "25 (Sumerian 40)",
    atk: 3,
    meleeArmor: "0 (Palmyran 1)",
    pierceArmor: 0,
    range: 0,
    los: 4,
    speed: "2.0 (Assy/Yama 2.6)",
    trainTime: "20s",
    upgradeFrom: "Khởi đầu",
    upgradeTo: "Không",
    counter: "Khai thác tài nguyên, xây nhà, câu voi, sửa chữa",
    counteredBy: "Ngựa dò, thú dữ, lính quấy rối",
    description: "Đơn vị kinh tế tối quan trọng của mọi đế chế. Sinh sản liên tục là chìa khóa lên đời nhanh."
  },
  {
    id: "clubman",
    name: "Lính Chùy",
    nameEn: "Clubman",
    age: 1,
    ageName: "Đời 1 (Stone Age)",
    building: "Doanh Trại (BB)",
    icon: "🏏",
    image: "images/units/clubman.png",
    category: "bo-binh",
    cost: { food: 50, wood: 0, gold: 0, stone: 0 },
    costText: "50 Thực",
    hp: 40,
    atk: 3,
    meleeArmor: 0,
    pierceArmor: 0,
    range: 0,
    los: 4,
    speed: 2.0,
    trainTime: "26s",
    upgradeFrom: "Cơ bản",
    upgradeTo: "Lính Rìu (Axeman - Đời 2)",
    counter: "Bắt dân đối phương khi bất ngờ, tự vệ",
    counteredBy: "Mọi đơn vị đời sau",
    description: "Lính bộ binh thô sơ đầu game, hiếm khi được sử dụng trong các trận đánh chuẩn đời 3."
  },
  {
    id: "fishing_boat",
    name: "Thuyền Đánh Cá",
    nameEn: "Fishing Boat",
    age: 1,
    ageName: "Đời 1 (Stone Age)",
    building: "Bến Cảng (Dock)",
    icon: "⛵",
    image: "images/units/fishing_boat.png",
    category: "thuy-binh",
    cost: { food: 0, wood: 50, gold: 0, stone: 0 },
    costText: "50 Gỗ",
    hp: 50,
    atk: 0,
    meleeArmor: 0,
    pierceArmor: 0,
    range: 0,
    los: 5,
    speed: 2.5,
    trainTime: "40s",
    upgradeFrom: "Cơ bản",
    upgradeTo: "Thuyền cá lớn (Đời 2)",
    counter: "Đánh bắt cá biển tăng sản lượng thức ăn",
    counteredBy: "Tàu chiến đối phương",
    description: "Đơn vị khai thác cá biển phục vụ kinh tế trên các bản đồ đảo (Islands)."
  },

  // ==================== ĐỜI 2: TOOL AGE ====================
  {
    id: "axeman",
    name: "Lính Rìu",
    nameEn: "Axeman",
    age: 2,
    ageName: "Đời 2 (Tool Age)",
    building: "Doanh Trại (BB)",
    icon: "🪓",
    image: "images/units/axeman.png",
    category: "bo-binh",
    cost: { food: 50, wood: 0, gold: 0, stone: 0 },
    costText: "50 Thực",
    hp: 50,
    atk: 5,
    meleeArmor: 0,
    pierceArmor: 0,
    range: 0,
    los: 4,
    speed: 2.0,
    trainTime: "26s",
    upgradeFrom: "Lính Chùy (100 Thực tại BB)",
    upgradeTo: "Lính Kiếm Ngắn (Đời 3)",
    counter: "Ngựa dò, quẩy đá nếu áp sát được",
    counteredBy: "Cung trần tầm xa, quẩy đá thả diều",
    description: "Bộ binh cơ bản của Đời 2, dùng trong các bài tấn công đời 2 (Tool rush)."
  },
  {
    id: "slinger",
    name: "Lính Quẩy Đá",
    nameEn: "Slinger",
    age: 2,
    ageName: "Đời 2 (Tool Age)",
    building: "Doanh Trại (BB)",
    icon: "🪨",
    image: "images/units/slinger.png",
    category: "cung-thu",
    cost: { food: 40, wood: 0, gold: 0, stone: 10 },
    costText: "40 Thực, 10 Đá",
    hp: 25,
    atk: "2 (+1.5 vs Cung thủ)",
    meleeArmor: 0,
    pierceArmor: 2,
    range: 4,
    los: 5,
    speed: 2.0,
    trainTime: "24s",
    upgradeFrom: "Cơ bản (Cần nâng Chợ BM)",
    upgradeTo: "Không",
    counter: "Cung trần, cung thủ tầm xa đời 2",
    counteredBy: "Ngựa dò áp sát, lính rìu",
    description: "Khắc tinh của các loại cung thủ đời 2 nhờ có sẵn 2 giáp tên và sát thương cộng thêm."
  },
  {
    id: "scout_cavalry",
    name: "Ngựa Dò",
    nameEn: "Scout Cavalry",
    age: 2,
    ageName: "Đời 2 (Tool Age)",
    building: "Nhà Ngựa (BL)",
    icon: "🐎",
    image: "images/units/scout_cavalry.png",
    category: "ky-binh",
    cost: { food: 100, wood: 0, gold: 0, stone: 0 },
    costText: "100 Thực (Yamato 75 Thực)",
    hp: 60,
    atk: 3,
    meleeArmor: 0,
    pierceArmor: 0,
    range: 0,
    los: 8,
    speed: 3.75,
    trainTime: "30s",
    upgradeFrom: "Cơ bản",
    upgradeTo: "Không",
    counter: "Dò bản đồ, bắt dân đi lẻ, câu voi, quấy nhiễu",
    counteredBy: "Lính rìu, quẩy đá tụ đông",
    description: "Đơn vị cơ động nhất đầu game; tầm nhìn rộng giúp kiểm soát mọi động thái của đối thủ."
  },
  {
    id: "bowman",
    name: "Cung Trần (Cung Gỗ)",
    nameEn: "Bowman",
    age: 2,
    ageName: "Đời 2 (Tool Age)",
    building: "Trường Bắn (BA)",
    icon: "🏹",
    image: "images/units/bowman.png",
    category: "cung-thu",
    cost: { food: 40, wood: 20, gold: 0, stone: 0 },
    costText: "40 Thực, 20 Gỗ",
    hp: 35,
    atk: 3,
    meleeArmor: 0,
    pierceArmor: 0,
    range: 5,
    los: 6,
    speed: 2.0,
    trainTime: "30s",
    upgradeFrom: "Cơ bản",
    upgradeTo: "Cung A 1 áo (Improved Bowman - Đời 3)",
    counter: "Lính rìu, nông dân từ xa",
    counteredBy: "Lính quẩy đá, ngựa dò áp sát",
    description: "Cung thủ đi bộ cơ bản; tụ đông có thể tạo áp lực tốt ở đời 2."
  },
  {
    id: "scout_ship",
    name: "Tàu Chiến Nhỏ (Scout Ship)",
    nameEn: "Scout Ship",
    age: 2,
    ageName: "Đời 2 (Tool Age)",
    building: "Bến Cảng (Dock)",
    icon: "🛶",
    image: "images/units/scout_ship.png",
    category: "thuy-binh",
    cost: { food: 0, wood: 135, gold: 0, stone: 0 },
    costText: "135 Gỗ",
    hp: 130,
    atk: 5,
    meleeArmor: 0,
    pierceArmor: 0,
    range: 5,
    los: 7,
    speed: 3.0,
    trainTime: "45s",
    upgradeFrom: "Cơ bản",
    upgradeTo: "Tàu chiến War Galley (Đời 3)",
    counter: "Thuyền cá, bắn tỉa dân ven biển",
    counteredBy: "Tháp canh ven biển, tàu chiến nâng cấp",
    description: "Chiến hạm sơ khai tranh giành quyền kiểm soát đường thủy ở Đời 2."
  },

  // ==================== ĐỜI 3: BRONZE AGE ====================
  {
    id: "chariot_archer",
    name: "Cung R (Ngựa Bắn Cung)",
    nameEn: "Chariot Archer",
    age: 3,
    ageName: "Đời 3 (Bronze Age)",
    building: "Trường Bắn (BA)",
    icon: "🏹",
    image: "images/units/chariot_archer.png",
    category: "cung-thu",
    cost: { food: 70, wood: 40, gold: 0, stone: 0 },
    costText: "70 Thực, 40 Gỗ",
    hp: "70 (Egy 93, Assy 75)",
    atk: "4 (+1 Hittite)",
    meleeArmor: 0,
    pierceArmor: "0 (+giáp BA)",
    range: "7 (+2 chặt gỗ BM)",
    los: 8,
    speed: 3.0,
    trainTime: "40s",
    upgradeFrom: "Yêu cầu nâng Bánh Xe (Wheel)",
    upgradeTo: "Không (Đời 4 giữ nguyên hoặc Cung R lửa)",
    counter: "Bộ binh, dân, thả diều ngựa chém khi tụ đông",
    counteredBy: "Ngựa chém áp sát, Lạc đà, Pháo cẩu đá",
    description: "Lực lượng tinh nhuệ phổ biến nhất game; cơ động, bắn tỉa dân, tụ đông tạo mưa tên hủy diệt."
  },
  {
    id: "cavalry",
    name: "Ngựa Chém Thường",
    nameEn: "Cavalry",
    age: 3,
    ageName: "Đời 3 (Bronze Age)",
    building: "Nhà Ngựa (BL)",
    icon: "⚔️",
    image: "images/units/cavalry.png",
    category: "ky-binh",
    cost: { food: 70, wood: 0, gold: 80, stone: 0 },
    costText: "70 Thực, 80 Vàng (Yamato 60 Vàng)",
    hp: "150 (Có Đầu Máu 172)",
    atk: "8 (+công BS lên 12)",
    meleeArmor: "1 (+giáp BS)",
    pierceArmor: "0 (+giáp tên)",
    range: 0,
    los: 5,
    speed: 3.25,
    trainTime: "40s",
    upgradeFrom: "Cơ bản đời 3",
    upgradeTo: "Ngựa chém nặng (Heavy Cav - Đời 4)",
    counter: "Cung R đi lẻ, dân, cẩu đá",
    counteredBy: "Lạc đà (khắc tinh), Phù thủy hú, Lính xiên",
    description: "Sốc sát thương cực cao, đồ sát dân trong nháy mắt; mũi nhọn tấn công đầu đời 3."
  },
  {
    id: "camelry",
    name: "Lạc Đà",
    nameEn: "Camelry",
    age: 3,
    ageName: "Đời 3 (Bronze Age)",
    building: "Nhà Ngựa (BL)",
    icon: "🐪",
    image: "images/units/camelry.png",
    category: "ky-binh",
    cost: { food: 70, wood: 0, gold: 60, stone: 0 },
    costText: "70 Thực, 60 Vàng",
    hp: 125,
    atk: "7 (+4 sát thương vs kỵ binh)",
    meleeArmor: 0,
    pierceArmor: 0,
    range: 0,
    los: 5,
    speed: "3.25 (Palmyran siêu tốc)",
    trainTime: "30s",
    upgradeFrom: "Cơ bản đời 3",
    upgradeTo: "Không",
    counter: "Ngựa chém BL, ngựa dò",
    counteredBy: "Cung R tụ đông, phù thủy, bộ binh",
    description: "Khắc tinh số 1 của mọi loại ngựa chém; giá rẻ hơn chém, chạy nhanh và bổ ngựa đối phương cực rát."
  },
  {
    id: "chariot",
    name: "Ngựa Sọc Đơn",
    nameEn: "Chariot",
    age: 3,
    ageName: "Đời 3 (Bronze Age)",
    building: "Nhà Ngựa (BL)",
    icon: "🛞",
    image: "images/units/chariot.png",
    category: "ky-binh",
    cost: { food: 70, wood: 40, gold: 0, stone: 0 },
    costText: "70 Thực, 40 Gỗ",
    hp: 100,
    atk: 7,
    meleeArmor: 0,
    pierceArmor: 0,
    range: 0,
    los: 5,
    speed: 3.25,
    trainTime: "40s",
    upgradeFrom: "Yêu cầu Bánh Xe (Wheel)",
    upgradeTo: "Ngựa Đạp Đôi (Đời 4)",
    counter: "Phù thủy (kháng hú cực cao), bia đỡ đạn cho cung",
    counteredBy: "Lạc đà, ngựa chém, lính xiên",
    description: "Chỉ tốn Gỗ và Thực, kháng phù thủy gần như miễn nhiễm; chuyên dùng càn quét phù thủy đối phương."
  },
  {
    id: "composite_bowman",
    name: "Cung A (2 Áo)",
    nameEn: "Composite Bowman",
    age: 3,
    ageName: "Đời 3 (Bronze Age)",
    building: "Trường Bắn (BA)",
    icon: "🎯",
    image: "images/units/composite_bowman.png",
    category: "cung-thu",
    cost: { food: 0, wood: 40, gold: 20, stone: 0 },
    costText: "40 Gỗ, 20 Vàng",
    hp: 45,
    atk: 5,
    meleeArmor: 0,
    pierceArmor: 0,
    range: "7 (Minoan lên 8-9)",
    los: 8,
    speed: 2.4,
    trainTime: "30s",
    upgradeFrom: "Cung A 1 áo (Improved Bowman)",
    upgradeTo: "Không",
    counter: "Thủ nhà, dồn sát thương tiêu diệt kỵ binh lao vào",
    counteredBy: "Pháo cẩu đá, ngựa chém áp sát",
    description: "Tầm xa tốt, tốc độ bắn nhanh; Minoan Cung A đứng tụ một góc tạo thành bức tường lửa bất khả xâm phạm."
  },
  {
    id: "broad_swordsman",
    name: "Lính Kiếm Bản Rộng",
    nameEn: "Broad Swordsman",
    age: 3,
    ageName: "Đời 3 (Bronze Age)",
    building: "Doanh Trại (BB)",
    icon: "🗡️",
    image: "images/units/broad_swordsman.png",
    category: "bo-binh",
    cost: { food: 35, wood: 0, gold: 15, stone: 0 },
    costText: "35 Thực, 15 Vàng",
    hp: "70 (Choson 150)",
    atk: 9,
    meleeArmor: 1,
    pierceArmor: 0,
    range: 0,
    los: 4,
    speed: 2.0,
    trainTime: "26s",
    upgradeFrom: "Short Swordsman",
    upgradeTo: "Long Swordsman (Đời 4)",
    counter: "Sọc đơn, phá hủy công trình nhanh",
    counteredBy: "Cung R thả diều, pháo cẩu",
    description: "Bộ binh chém bổ củi; Roman chém nhanh +33%, Choson máu dày tới 150 HP."
  },
  {
    id: "hoplite",
    name: "Lính Xiên (Hoplite)",
    nameEn: "Hoplite",
    age: 3,
    ageName: "Đời 3 (Bronze Age)",
    building: "Hàn Lâm Viện (BY)",
    icon: "🛡️",
    image: "images/units/hoplite.png",
    category: "bo-binh",
    cost: { food: 60, wood: 0, gold: 40, stone: 0 },
    costText: "60 Thực, 40 Vàng",
    hp: "120 (Carthaginian 150)",
    atk: 17,
    meleeArmor: 5,
    pierceArmor: 0,
    range: 0,
    los: 4,
    speed: "1.5 (Greek chạy 1.95)",
    trainTime: "36s",
    upgradeFrom: "Cơ bản tại BY",
    upgradeTo: "Phalanx (Đời 4)",
    counter: "Toàn bộ kỵ binh, cận chiến",
    counteredBy: "Cung thủ thả diều, phù thủy từ xa",
    description: "Chỉ số cận chiến vượt trội (Công 17, Giáp 5); Greek chạy nhanh +30% đuổi kịp cả bộ binh đối phương."
  },
  {
    id: "stone_thrower",
    name: "Pháo Bắn Đá Nhỏ",
    nameEn: "Stone Thrower",
    age: 3,
    ageName: "Đời 3 (Bronze Age)",
    building: "Xưởng Pháo (BK)",
    icon: "☄️",
    image: "images/units/stone_thrower.png",
    category: "phao-binh",
    cost: { food: 0, wood: 180, gold: 80, stone: 0 },
    costText: "180 Gỗ, 80 Vàng (Macedonian 90G, 40V)",
    hp: "150 (Hittite 300)",
    atk: "50 (Nổ lan)",
    meleeArmor: 0,
    pierceArmor: 0,
    range: 10,
    los: 10,
    speed: 1.5,
    trainTime: "50s",
    upgradeFrom: "Cơ bản tại BK",
    upgradeTo: "Catapult (Đời 4)",
    counter: "Cung thủ tụ đông, tháp canh",
    counteredBy: "Ngựa chém luồn vào, pháo tép",
    description: "Vũ khí giải tán đám đông số 1; Hittite máu x2 (300 HP), Sumerian bắn nhanh gấp đôi."
  },
  {
    id: "ballista",
    name: "Pháo Tép / Pháo Tên (Ballista)",
    nameEn: "Ballista",
    age: 3,
    ageName: "Đời 3 (Bronze Age)",
    building: "Xưởng Pháo (BK)",
    icon: "🏹",
    image: "images/units/ballista.png",
    category: "phao-binh",
    cost: { food: 0, wood: 100, gold: 80, stone: 0 },
    costText: "100 Gỗ, 80 Vàng (Roman rẻ gỗ, Macedon -50%)",
    hp: 55,
    atk: "40 (Xuyên thẳng)",
    meleeArmor: 0,
    pierceArmor: 0,
    range: 10,
    los: 10,
    speed: 1.5,
    trainTime: "50s",
    upgradeFrom: "Cơ bản tại BK",
    upgradeTo: "Helepolis (Đời 4)",
    counter: "Bộ binh, voi, mục tiêu xếp thẳng hàng",
    counteredBy: "Cẩu đá nổ lan, kỵ binh áp sát",
    description: "Bắn tên xuyên thẳng tốc độ cao; vũ khí khắc chế voi và lính xiên hiệu quả."
  },
  {
    id: "priest",
    name: "Phù Thủy (Thầy Tu)",
    nameEn: "Priest",
    age: 3,
    ageName: "Đời 3 (Bronze Age)",
    building: "Đền Thờ (BP)",
    icon: "🧙‍♂️",
    image: "images/units/priest.png",
    category: "phu-thuy",
    cost: { food: 0, wood: 0, gold: 125, stone: 0 },
    costText: "125 Vàng (Choson 85 Vàng)",
    hp: 25,
    atk: "Thu phục (Hú)",
    meleeArmor: 0,
    pierceArmor: 0,
    range: "9 (Egyptian 12)",
    los: 10,
    speed: 1.5,
    trainTime: "50s",
    upgradeFrom: "Cơ bản tại BP",
    upgradeTo: "Các phép nâng cấp tại BP",
    counter: "Ngựa chém, Lạc đà, Voi, đơn vị đắt tiền",
    counteredBy: "Sọc đơn, Đạp đôi (kháng hú), Cung R tầm xa",
    description: "Thu phục quân đối phương và hồi máu cho quân mình; vũ khí lật kèo thần thánh."
  },

  // ==================== ĐỜI 4: IRON AGE ====================
  {
    id: "scythe_chariot",
    name: "Ngựa Đạp Đôi",
    nameEn: "Scythe Chariot",
    age: 4,
    ageName: "Đời 4 (Iron Age)",
    building: "Nhà Ngựa (BL)",
    icon: "🛞",
    image: "images/units/scythe_chariot.png",
    category: "ky-binh",
    cost: { food: 75, wood: 75, gold: 0, stone: 0 },
    costText: "75 Thực, 75 Gỗ",
    hp: 120,
    atk: "9 (Chém lan diện rộng)",
    meleeArmor: 2,
    pierceArmor: 2,
    range: 0,
    los: 5,
    speed: 3.25,
    trainTime: "40s",
    upgradeFrom: "Sọc Đơn (Nâng cấp tại BL)",
    upgradeTo: "Tối đa",
    counter: "Nông dân, bộ binh, cung thủ tụ đám đông, phù thủy",
    counteredBy: "Xiên thần Centurion, Voi thần, Bắn đá to",
    description: "Vua quân rác đời 4; chỉ tốn Gỗ và Thực, chém lan diện rộng càn quét tan hoang ruộng lúa và căn cứ."
  },
  {
    id: "cataphract",
    name: "Ngựa Chém Thần",
    nameEn: "Cataphract",
    age: 4,
    ageName: "Đời 4 (Iron Age)",
    building: "Nhà Ngựa (BL)",
    icon: "⚔️",
    image: "images/units/cataphract.png",
    category: "ky-binh",
    cost: { food: 70, wood: 0, gold: 80, stone: 0 },
    costText: "70 Thực, 80 Vàng (Yamato 60 Vàng)",
    hp: 180,
    atk: "12 (+5 cộng dồn vs bộ binh)",
    meleeArmor: 3,
    pierceArmor: 0,
    range: 0,
    los: 5,
    speed: 3.25,
    trainTime: "40s",
    upgradeFrom: "Ngựa Chém Nặng (Heavy Cav)",
    upgradeTo: "Tối đa",
    counter: "Bộ binh, cung thủ, phá sập nhà quân",
    counteredBy: "Lạc đà, Phù thủy hú, Xiên thần",
    description: "Kỵ binh bọc thép hoàng gia; giáp trâu máu dày, đồ sát bộ binh và cung tên trong tích tắc."
  },
  {
    id: "armored_elephant",
    name: "Voi Húc Thần (Voi Bọc Thép)",
    nameEn: "Armored Elephant",
    age: 4,
    ageName: "Đời 4 (Iron Age)",
    building: "Nhà Cận Chiến (BL)",
    icon: "🐘",
    image: "images/units/armored_elephant.png",
    category: "ky-binh",
    cost: { food: 170, wood: 0, gold: 40, stone: 0 },
    costText: "170 Thực, 40 Vàng (Phoenician 127T, 30V)",
    hp: "600 (Carthaginian 750)",
    atk: "18 (Sát thương lan diện rộng)",
    meleeArmor: 2,
    pierceArmor: 1,
    range: 0,
    los: 5,
    speed: "1.5 (Persian 2.25 chạy như ngựa)",
    trainTime: "50s",
    upgradeFrom: "War Elephant (Voi chiến)",
    upgradeTo: "Tối đa",
    counter: "Công trình, quân cận chiến, nghiền nát vật cản",
    counteredBy: "Phù thủy thu phục, Xiên thần, Bắn đá to",
    description: "Xe tăng bọc thép cổ đại máu 600 - 750 HP; Persian chạy nhanh như ngựa, Carthage trâu 750 HP húc bay mọi thứ."
  },
  {
    id: "elephant_archer",
    name: "Voi Bắn Tên",
    nameEn: "Elephant Archer",
    age: 4,
    ageName: "Đời 4 (Iron Age)",
    building: "Trường Bắn (BA)",
    icon: "🐘",
    image: "images/units/elephant_archer.png",
    category: "cung-thu",
    cost: { food: 180, wood: 0, gold: 60, stone: 0 },
    costText: "180 Thực, 60 Vàng (Phoenician 135T)",
    hp: "600 (Carthaginian 750)",
    atk: 6,
    meleeArmor: 0,
    pierceArmor: 0,
    range: "7 (+chặt gỗ)",
    los: 8,
    speed: 1.75,
    trainTime: "50s",
    upgradeFrom: "Cơ bản tại BA Đời 4",
    upgradeTo: "Tối đa",
    counter: "Bắn tầm xa hỗ trợ, hút hỏa lực",
    counteredBy: "Phù thủy, Xiên thần, Bắn đá to",
    description: "Tháp canh di động khổng lồ; máu trâu 600 - 750 HP vừa che chắn vừa bắn tỉa cực kỳ khó chịu."
  },
  {
    id: "heavy_horse_archer",
    name: "Ngựa Cung C Thần",
    nameEn: "Heavy Horse Archer",
    age: 4,
    ageName: "Đời 4 (Iron Age)",
    building: "Trường Bắn (BA)",
    icon: "🏹",
    image: "images/units/heavy_horse_archer.png",
    category: "cung-thu",
    cost: { food: 50, wood: 0, gold: 70, stone: 0 },
    costText: "50 Thực, 70 Vàng",
    hp: 90,
    atk: 8,
    meleeArmor: 0,
    pierceArmor: 1,
    range: "7 (+chặt gỗ)",
    los: 8,
    speed: 3.75,
    trainTime: "40s",
    upgradeFrom: "Horse Archer",
    upgradeTo: "Tối đa",
    counter: "Cơ động rỉa máu, bắn tỉa pháo và bộ binh",
    counteredBy: "Ngựa đạp đôi, Ngựa chém thần",
    description: "Cung kỵ binh chạy nhanh nhất game; sát thương tầm xa ấn tượng."
  },
  {
    id: "legion",
    name: "Lính Kiếm Thần (Legion)",
    nameEn: "Legion",
    age: 4,
    ageName: "Đời 4 (Iron Age)",
    building: "Doanh Trại (BB)",
    icon: "🗡️",
    image: "images/units/legion.png",
    category: "bo-binh",
    cost: { food: 35, wood: 0, gold: 15, stone: 0 },
    costText: "35 Thực, 15 Vàng",
    hp: "140 (Choson 240)",
    atk: 13,
    meleeArmor: 2,
    pierceArmor: 1,
    range: 0,
    los: 4,
    speed: 2.0,
    trainTime: "26s",
    upgradeFrom: "Long Swordsman",
    upgradeTo: "Tối đa",
    counter: "Phá hủy công trình, chém sọc đơn, đè bẹp cung thủ",
    counteredBy: "Bắn đá to, Voi thần, Cung thả diều",
    description: "Chiến binh quân đoàn La Mã; Choson máu dày tới 240 HP, Roman chém nhanh như máy khâu."
  },
  {
    id: "centurion",
    name: "Xiên Thần (Centurion)",
    nameEn: "Centurion",
    age: 4,
    ageName: "Đời 4 (Iron Age)",
    building: "Hàn Lâm Viện (BY)",
    icon: "🛡️",
    image: "images/units/centurion.png",
    category: "bo-binh",
    cost: { food: 60, wood: 0, gold: 40, stone: 0 },
    costText: "60 Thực, 40 Vàng",
    hp: "160 (Carthaginian 200)",
    atk: 30,
    meleeArmor: 8,
    pierceArmor: 0,
    range: 0,
    los: 4,
    speed: "1.5 (Greek lướt gió 1.95)",
    trainTime: "36s",
    upgradeFrom: "Phalanx (Đời 4)",
    upgradeTo: "Tối đa",
    counter: "Toàn bộ kỵ binh, voi húc, mọi đơn vị cận chiến",
    counteredBy: "Phù thủy tầm xa, Cẩu đá to",
    description: "Chiến binh giáp trụ nặng có chỉ số cận chiến Công 30 Giáp 8 cao nhất game; Greek lướt gió đâm thủng mọi đội hình."
  },
  {
    id: "heavy_catapult",
    name: "Pháo Cẩu Đá To (Heavy Catapult)",
    nameEn: "Heavy Catapult",
    age: 4,
    ageName: "Đời 4 (Iron Age)",
    building: "Xưởng Pháo (BK)",
    icon: "☄️",
    image: "images/units/heavy_catapult.png",
    category: "phao-binh",
    cost: { food: 0, wood: 180, gold: 80, stone: 0 },
    costText: "180 Gỗ, 80 Vàng (Macedonian 90G, 40V)",
    hp: "175 (Hittite 350)",
    atk: "60 (Sát thương lan diện rộng cực đại)",
    meleeArmor: 0,
    pierceArmor: 0,
    range: 12,
    los: 12,
    speed: 1.5,
    trainTime: "50s",
    upgradeFrom: "Catapult",
    upgradeTo: "Tối đa",
    counter: "Xóa sổ toàn bộ cụm quân, thổi bay công trình từ xa",
    counteredBy: "Ngựa chém thần, Ngựa đạp đôi áp sát",
    description: "Hỏa lực tầm xa tối thượng; một phát bắn có thể xóa sổ hàng chục đơn vị trong bán kính nổ."
  },
  {
    id: "helepolis",
    name: "Pháo Liên Thanh (Helepolis)",
    nameEn: "Helepolis",
    age: 4,
    ageName: "Đời 4 (Iron Age)",
    building: "Xưởng Pháo (BK)",
    icon: "🏹",
    image: "images/units/helepolis.png",
    category: "phao-binh",
    cost: { food: 0, wood: 100, gold: 80, stone: 0 },
    costText: "100 Gỗ, 80 Vàng (Roman rẻ gỗ, Macedon -50%)",
    hp: 55,
    atk: "40 (Bắn xuyên phá liên tục)",
    meleeArmor: 0,
    pierceArmor: 0,
    range: 10,
    los: 10,
    speed: 1.5,
    trainTime: "50s",
    upgradeFrom: "Ballista",
    upgradeTo: "Tối đa",
    counter: "Voi thần, Xiên thần, càn quét đường thẳng",
    counteredBy: "Cẩu đá to, Ngựa chém thần áp sát",
    description: "Tốc độ bắn cực nhanh như súng máy liên thanh; giải pháp triệt hạ các loại quân trâu máu."
  },
  {
    id: "juggernaught",
    name: "Tàu Pháo Thần (Juggernaught)",
    nameEn: "Juggernaught",
    age: 4,
    ageName: "Đời 4 (Iron Age)",
    building: "Bến Cảng (Dock)",
    icon: "🚢",
    image: "images/units/juggernaught.png",
    category: "thuy-binh",
    cost: { food: 0, wood: 135, gold: 75, stone: 0 },
    costText: "135 Gỗ, 75 Vàng",
    hp: 200,
    atk: "40 (Pháo nổ lan)",
    meleeArmor: 0,
    pierceArmor: 0,
    range: 10,
    los: 11,
    speed: 2.5,
    trainTime: "50s",
    upgradeFrom: "Catapult Trireme",
    upgradeTo: "Tối đa",
    counter: "Công trình ven biển, tàu chiến địch",
    counteredBy: "Cẩu đá to trên đất liền",
    description: "Pháo hạm tầm xa tối thượng trên biển, bắn nát các công trình ven bờ từ khoảng cách 10 ô."
  }
];
